version: '3.8'
services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - catalogdb_volume:/data/db
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "1200:6379"
  discountdb:
    container_name: discountdb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - discountdb_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=discountdb
  identitydb:
    container_name: identitydb
    user: root
    restart: always
    ports:
      - "1400:1433"
    volumes:
      - identitydb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12*
  orderdb:
    container_name: orderdb
    user: root
    restart: always
    ports:
      - "1401:1433"
    volumes:
      - orderdb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12*
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmquser
      - RABBITMQ_DEFAULT_PASS=Password12*
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__ConnectionString=mongodb://catalogdb:27017
      - RabbitMQ__URL=rabbitmq
      - Token__Issuer=http://identity.api:5004
    ports:
      - "5019:80"
    depends_on:
      - catalogdb
      - rabbitmq
  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RedisSettings__Host=basketdb
      - RabbitMQ__URL=rabbitmq
      - Token__Issuer=http://identity.api:5004
    ports:
      - "5021:80"
    depends_on:
      - basketdb
      - rabbitmq
  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=discountdb;Port=5433;Database=discountdb;User ID=postgres;Password=postgres;
      - Token__Issuer=http://identity.api:5004
    ports:
      - "5022:80"
    depends_on:
      - discountdb
  identity.api:
    container_name: identity.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=identitydb;Database=IdentityDb;User=sa;Password=Password12*;Encrypt=false;
    ports:
      - "5004:80"
    depends_on:
      - identitydb
  order.api:
    container_name: order.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=orderdb;Database=Orderdb;User=sa;Password=Password12*;Encrypt=false;
      - Token__Issuer=http://identity.api:5004
      - RabbitMQ__URL=rabbitmq
    ports:
      - "5023:80"
    depends_on:
      - orderdb
      - rabbitmq
  payment.api:
    container_name: payment.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Token__Issuer=http://identity.api:5004
      - RabbitMQ__URL=rabbitmq
    ports:
      - "5024:80"
    depends_on:
      - rabbitmq
  photostock.api:
    container_name: photostock.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Token__Issuer=http://identity.api:5004
    ports:
      - "5020:80"
    volumes:
      - type: bind
        source: C:\Users\balib\photos
        target: /app/wwwroot/photos
volumes:
  catalogdb_volume:
  discountdb_volume:
  identitydb_volume:
  orderdb_volume: