version: '3.8'
services:
  catalog.api:
    image: catalog_api_image
    build: 
      context: .
      dockerfile: Services/Catalog/Course.Catalog.Service.Api/Dockerfile
  basket.api:
    image: basket_api_image
    build: 
      context: .
      dockerfile: Services/Basket/Course.Basket.Service.Api/Dockerfile
  discount.api:
    image: discount_api_image
    build: 
      context: .
      dockerfile: Services/Discount/Course.Discount.Service.Api/Dockerfile
  identity.api:
    image: identity_api_image
    build: 
      context: .
      dockerfile: IdentityServer/Course.IdentityServer/Dockerfile
  order.api:
    image: order_api_image
    build: 
      context: .
      dockerfile: Services/Order/Course.Order.API/Dockerfile
  payment.api:
    image: payment_api_image
    build: 
      context: .
      dockerfile: Services/FakePayment/Course.FakePayment.Service.Api/Dockerfile
  photostock.api:
    image: photostock_api_image
    build: 
      context: .
      dockerfile: Services/PhotoStock/Course.PhotoStock.Service.Api/Dockerfile
  catalogdb:
    image: mongo
  basketdb:
    image: redis:latest
  discountdb:
    image: postgres
  identitydb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  rabbitmq:
    image: rabbitmq:management
volumes:
  catalogdb_volume:
  discountdb_volume:
  identitydb_volume:
  orderdb_volume: