version: '3.4'

services:
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  # identity.server:
  #   environment:
  #     - ASPNETCORE_URLS="https://+:5003;http://+:5002"
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORT=5002
  #     - ASPNETCORE_HTTPS_PORT=5003
  #   ports:
  #     - "5002:5002"
  #     - "5003:5003"
  #   volumes:
  #     - ${APPDATA}\Microsoft\UserSecrets\:/root/.microsoft/usersecrets
  #     - ${APPDATA}\.aspnet\https:/root/.aspnet/https/